
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 26 14:30:29 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_PLUS = 2;
  public static final int TK_VAL = 7;
  public static final int TK_DONE = 6;
  public static final int TK_DIV = 5;
  public static final int error = 1;
  public static final int TK_MINUS = 3;
  public static final int TK_MULT = 4;
  public static final int EOF = 0;
}

