
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 26 15:46:14 CEST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_EXP = 15;
  public static final int TK_DONE = 7;
  public static final int TK_PI = 19;
  public static final int TK_DIV = 5;
  public static final int TK_PLUS = 2;
  public static final int TK_TAN = 12;
  public static final int TK_SQRT = 13;
  public static final int EOF = 0;
  public static final int TK_VAL = 18;
  public static final int TK_SIN = 10;
  public static final int error = 1;
  public static final int TK_UMINUS = 6;
  public static final int TK_LN = 14;
  public static final int TK_COS = 11;
  public static final int TK_MULT = 4;
  public static final int TK_E = 20;
  public static final int TK_OPBRA = 8;
  public static final int TK_MINUS = 3;
  public static final int TK_POW = 16;
  public static final int TK_CLBRA = 9;
  public static final int TK_ID = 21;
  public static final int TK_ASSIGN = 17;
}

